### ISSUE TITLE
Add Binding drawn elements to a model

### ISSUE THREAD

**Issue by kstraszewski** [Asymmetrik/ngx-leaflet-draw#27]
Is there any option to get LatLng from drawn objects to save them in database? Like binding drawn data to an variable?

**Comment by reblace** [comment]
For now, there are no angular bindings. However, you can use one of the approaches described in the angular2-leaflet README [1] to get a reference to the map instance and then listen for the draw/edit events [2].

That will give you access to the drawn objects as they are drawn so you can do whatever you want with them.

```js
map.on(L.Draw.Event.CREATED; function (e) {
   var type = e.layerType;
       layer = e.layer;
   if (type === 'marker') {
       // Do marker specific actions
   }
   // Do whatever else you need to. (save to db; add to map etc)
   map.addLayer(layer);
});
```

[1] https://github.com/Asymmetrik/angular2-leaflet#getting-a-reference-to-the-map
[2] https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest.html#l-draw-event

**Comment by reblace** [comment]
Gonna close this as resolved, let me know if you have any more issues and thanks for using the component!

**Comment by smedasn** [comment]
Thanks for the hint @reblace . I was able to store the annotations in my server backend with L.Draw.Events. When I want to restore the annotations in a different session, do I have to add them to a specific layer (featureGroup) to enable edit and remove on the restored annotations?

Just for my understanding. After edit and remove works there seems to be a exisiting database object / array. Would it be possible to just expose this db/array?
It would be less code and less error prone to just use this object to store it in a own db.
