### ISSUE TITLE
data binding with color for exemple

### ISSUE THREAD

**Issue by mylen** [Asymmetrik/ngx-leaflet-draw#31]
I would like to modify the color of the drawn objets and though I could use data binding.

I have a color variable in my component controller:
```
import { Component } from '@angular/core';
import * as L from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  color = '#F00';
  drawOptions = {
    position: 'topleft',
    draw: {
      polyline: {
        shapeOptions: {
          color: this.color
        }
      }
    }
  };
  options = {
    layers: [
      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
    ],
    zoom: 5,
    center: L.latLng([ 46.879966, -121.726909 ])
  };
  colorChange(event) {
    alert(event);
  }
}
```
Now, I am using a color picker in order to change the color of the line. But when I modifiy the color value, the color of the line is stuck with the initial color.

How can I use data binding in order to be able to use another color ?

**Comment by reblace** [comment]
The color property you're providing is being passed into the Leaflet.draw toolbar constructor. Changes aren't tracked after initialization.

To achieve what you're trying to do, you should provide your own feature group, and then use the ```setStyle``` function on the feature group to set the color of all of the shapes that have been drawn.

http://leafletjs.com/reference-1.2.0.html#featuregroup-setstyle

**Comment by mylen** [comment]
Actualy, I'm pretty happy with the fact that the color is set once for all. What I would like to achieve is to be able to change the constructor options, how do I get a reference to the controller objects and change the color state?

**Comment by mylen** [comment]
ok, I guess I'll go like this: https://github.com/Leaflet/Leaflet.draw/issues/645

**Comment by mylen** [comment]
I've tried to do that:
```
  colorChange(event) {
    L.DrawToolbar.setOptions(this.drawOptions);
    console.log("drawOptions: " + this.drawOptions);
  }
```
I get the error:

> C:/utils/cygwin64/home/A140980/canimap-angular/lf-canimap/src/app/app.component.ts (41,7): Property 'DrawToolbar' does not exist on type 'typeof "c:/utils/cygwin64/home/a140980/canimap-angular/lf-canimap/node_modules/@types/leaflet/ind...'.

**Comment by reblace** [comment]
It sounds like you want to change the color, but only have it change for new shapes? If that's the case, you probably want to add the drawn shapes to the map yourself, and set the color based on the currently picked color.

To do this, you'll want to do the following:

1. Prevent the ngx-leaflet-draw plugin from adding shapes automatically to the map
2. Register for the created event and add the shape manually to your map

For 1 - You'll have to keep the ngx-leaflet-draw plugin from adding the shapes to the map by providing your own FeatureGroup which you don't add to the map. That way, the shapes won't get automatically added to the map.

```
featureGroup = new L.FeatureGroup();
drawOptions = {
    position: 'topright',
    featureGroup: this.featureGroup
};
```

For 2 - You'll need to set the color on the shape

```
map.on(L.Draw.Event.CREATED, (e) => {
    e.layer.setStyle({ color: currentColor });
    map.addLayer(e.layer);
});

```


You might also be able to do this by just listening to the CREATED event and setting the style and not worrying about the feature group stuff. I'd have to test it out to be sure.

**Comment by mylen** [comment]
Thank's for you help, really apreciate it, will try to figure that out

**Comment by mylen** [comment]
ok, I managed to get it working thank's to your input !
```
import { Component } from '@angular/core';
import * as L from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  map = L.Map;
  title = 'app';
  color = '#F00';
  options = {
    layers: [
      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
    ],
    zoom: 5,
    center: L.latLng([ 46.879966, -121.726909 ])
  };
  featureGroup = new L.FeatureGroup();
  drawOptions = {
    position: 'topleft',
    featureGroup: this.featureGroup
  };

  onMapReady(map: L.Map) {
    this.map = map;
    this.map.on(L.Draw.Event.CREATED, (e) => {
      e.layer.setStyle({ color: this.color });
      this.map.addLayer(e.layer);
    });
  }
}

```

**Comment by reblace** [comment]
Awesome, glad it worked!

**Comment by mylen** [comment]
For the record, I've modified the function in order to use @types/leaflet

```typescript
  onMapReady(map: Map) {
    this.map = map;
    this.map.on(L.Draw.Event.CREATED, (e: LayerEvent) => {
      console.log(e);
      try {
        let path:Path = <Path>e.layer;
        path.setStyle({ color: this.color });
        this.map.addLayer(<Layer>path);
      } catch (e) {
        console.log(e);
      }
    });
  }

```
