### ISSUE TITLE
integrate leaflet illustrate

### ISSUE THREAD

**Issue by mylen** [Asymmetrik/ngx-leaflet-draw#33]
I've got a feature request to integrate Leaflet.Illustrate as a fork of ngx-leaflet-draw

https://github.com/justinmanley/Leaflet.Illustrate

That would be an awsome add-on, I'll try to do it, I might need some advices though

**Comment by reblace** [comment]
The best approach would be to create a new repo (could start as a copy of this one) that extends the @asymmetrik/ngx-leaflet project to add new directives for integrating Leaflet.Illustrate. That's basically the same approach that this package takes.

Is there an active fork of Leaflet.Illustrate? The repo looks like it has been inactive for a while.

**Comment by mylen** [comment]
Thanks for your advice, I'll check if there is nothing new

**Comment by reblace** [comment]
Closing this with the response that this would be best addressed by wrapping Leaflet.Illustrate in a directive that extends the functionality of ngx-leaflet (as opposed to extending ngx-leaflet-draw).
