### ISSUE TITLE
Enable distance preview in all annotations

### ISSUE THREAD

**Issue by smedasn** [Asymmetrik/ngx-leaflet-draw#37]
the circle annoations has a great feature where one can see the diameter. would love to see this kind of distance preview also at the other annotations.

**Comment by reblace** [comment]
ngx-leaflet-draw is just a thin wrapper around Leaflet.draw to make it easy to use with angular.io. 

You should probably put the feature request in with them here: https://github.com/Leaflet/Leaflet.draw.

Thanks for using the plugin though!
