### ISSUE TITLE
index.d.ts, found version 4, expected 3, resolving symbol

### ISSUE THREAD

**Issue by smedasn** [Asymmetrik/ngx-leaflet-draw#43]
When I update to the latest version via "npm update" I get the following error.

node_modules/@asymmetrik/ngx-leaflet-draw/dist/index.d.ts, found version 4, expected 3, resolving symbol.

I fixed this issue temporarily with npm install @asymmetrik/ngx-leaflet-draw@2.6.0

My package.json dependencies:

` "@angular/animations": "^4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "@asymmetrik/ngx-leaflet": "^2.6.1",
    "@asymmetrik/ngx-leaflet-draw": "^2.7.0",
    "angular2-busy": "^2.0.4",
    "core-js": "^2.5.3",
    "hammerjs": "^2.0.8",
    "leaflet": "^1.3.1",
    "leaflet-draw": "^0.4.14",
    "ngx-file-drop": "^2.0.4",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.20"`

**Comment by reblace** [comment]
Yeah, sorry, I didn't push out a patch to revert the upgrade to ng5 on leaflet-draw 2.x.

The long story is I upgraded the plugin to ng5 with release 2.7, but didn't realize until after the fact that it wasn't a backward compatible change. So, if you're still on ng4, you'll want to stick with 2.6. Once I realized that it was not backward compatible, I released 3.x with ng5, but I never went back and released 2.7.1 to roll back to ng4.

**Comment by smedasn** [comment]
Thank you for clarification

**Comment by reblace** [comment]
I just pushed an new patch 2.7.1 that reverts to ng4 build on the 2.x branch.
Update and let me know if you still have any issues.

**Comment by reblace** [comment]
I'm gonna close this cause I think this issue is now resolved. Feel free to reopen if you have issues with the latest patch version of 2.7.
