### ISSUE TITLE
how to obtain reference to leafletDraw?

### ISSUE THREAD

**Issue by AndreasSchmid1** [Asymmetrik/ngx-leaflet-draw#50]
Is it possible to get the reference to the leafletdraw control similar to the map control?

I am searching for an event like this  (leafletDrawReady)="onDrawReady($event)"

The reason behind is I want to change the drawing options dynamically during runtime.

After I have the reference of the leafletdraw control I'll try to utilize the "setDrawingOptions" described here https://github.com/Leaflet/Leaflet.draw

**Comment by reblace** [comment]
I'll make a note to add (leafletDrawReady) like you reference. In the meantime, you should be able to use ```@ViewChild``` in the component that contains your map - similar to what is described here:

https://github.com/Asymmetrik/ngx-leaflet/issues/43

**Comment by Zahma** [comment]
@reblace thank you for the answer I did exactly what you said, but my drawControl is returned as undefined.
I declared this in my component class:
    @ViewChild(LeafletDrawDirective) leafletDirective: LeafletDrawDirective;
and I call leafletDirective.drawControl from onMapReady of leaflet.

**Comment by reblace** [comment]
I'm working on a minor release to add the "drawControlReady" event emitter, should make it easy to do what you need. I think I'll have it out today or tomorrow.

**Comment by reblace** [comment]
3.1.0 contains the changes you should need to get a reference to the draw control. Let me know if you run into any issues.
