### ISSUE TITLE
Cannot read property 'Event' of undefined at LeafletDrawDirective.ngOnInit 

### ISSUE THREAD

**Issue by Koushik-Sarkar** [Asymmetrik/ngx-leaflet-draw#51]
I am using ngx-leaflet-draw and ngx-leaflet. The map is coming on the div. Also, the Drawing option is coming. But the draw lines (Also, circle, rectangle, line etc) is not persisting on the screen. 

![ngx-angular-draw](https://user-images.githubusercontent.com/24456854/36716344-13fa3344-1bc0-11e8-849d-63bcb2ed0bfc.gif)

On the console, we are getting an error. 

![image](https://user-images.githubusercontent.com/24456854/36715863-10f86690-1bbe-11e8-98f2-ba9b106a26b1.png)

This is coming from below part of the code in the file leaflet-draw.directive.ts.

````
		// Register the main handler for events coming from the draw plugin
		this.leafletDirective.getMap().on(L.Draw.Event.CREATED, (e: any) => {
			const layer = (e as L.DrawEvents.Created).layer;
			this.featureGroup.addLayer(layer);
		});
	}
````
Please help.

**Comment by reblace** [comment]
Can you give some details about your setup? angular-cli? What versions of Leaflet and Leaflet.draw?

**Comment by Zahma** [comment]
@Koushik-Sarkar  can you let us know of which versions of leaflet and leaflet draw you are using ? thank you

**Comment by reblace** [comment]
This sounds like a problem with versions of libraries and/or versions of typings. Particularly if it compiles, but then fails at runtime, it sounds like it might be an issue with typings.

**Comment by reblace** [comment]
Haven't heard back, gonna close this. See above comments if you're having this issue.
