### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by Zahma** [Asymmetrik/ngx-leaflet-draw#52]
hello,
I was wondering which version is compatible with angular 4 ?
my package.json contains the following dependencies:

> "@asymmetrik/ngx-leaflet": "3",
> "@asymmetrik/ngx-leaflet-draw": "3.0.0",
> "leaflet": "1.2",
> "leaflet-draw": "0.4",
> "types/leaflet": "1.2",
> "types/leaflet-draw": "0.4"

but its not working .

**Comment by reblace** [comment]
The 3.x versions require Angular 5

If you want to use Angular 4, stick with 
@asymmetrik/ngx-leaflet 2.x
@asymmetrik/ngx-leaflet-draw 2.x

**Comment by reblace** [comment]
Answered the question, so gonna close this. Thanks!
