### ISSUE TITLE
push drawn Layers into leafletLayers

### ISSUE THREAD

**Issue by Zahma** [Asymmetrik/ngx-leaflet-draw#55]
its logic that the drawn layers should be appended to leafletlayers, so what I did basically is the following:

```
this.map.on(L.Draw.Event.CREATED, (e) => {
            let layer: any = e.layer;
            this.layers.push(layer);  
 });
```

the problem is that the push is not instantly reflected into the map. A click event should be performed before saying the layer on the map. why is that happening ?!

**Comment by reblace** [comment]
Closing this as answered.
