### ISSUE TITLE
Draw toolbox text overflow

### ISSUE THREAD

**Issue by marznafri** [Asymmetrik/ngx-leaflet-draw#59]
![issue_1](https://user-images.githubusercontent.com/41895541/43386811-5d23c808-9417-11e8-8dc4-6658b0130b8a.png)
 Hi, I have setup ngx-leaflet-draw on my local, on Angular 6, and when trying the drawing function the toolbox come out looking like this. Is there any pointers that you can give on why this is happening?

**Comment by reblace** [comment]
It looks like the styles might be missing for leaflet draw. Did you follow the instructions for loading the styles (https://github.com/Asymmetrik/ngx-leaflet-draw#import-the-leaflet-stylesheet)?

**Comment by reblace** [comment]
Closing this as answered
