### ISSUE TITLE
LeafletUtil library doesn't work for me

### ISSUE THREAD

**Issue by beubzz** [Asymmetrik/ngx-leaflet-draw#67]
on file @asymmetrik\ngx-leaflet-draw\dist\leaflet-draw\core\leaflet-draw.directive.js. On the line 13, if it's possible to change this line :
import { LeafletDirective, LeafletDirectiveWrapper, LeafletUtil } from '@asymmetrik/ngx-leaflet';

Into this two line : 
import { LeafletDirective, LeafletDirectiveWrapper } from '@asymmetrik/ngx-leaflet';
import { LeafletUtil } from '@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.util';

Other way, the leafletUtil library doesn't work for me ...

**Comment by Zscfg** [comment]
Yea, it's true. Angular CLI can not find this class with an existing import.

**Comment by reblace** [comment]
The latest version of `@asymmetrik/ngx-leaflet` exports LeafletUtil correctly, so you shouldn't need this change for it to work. Can you verify you're using at least `@asymmetrik/ngx-leaflet@5.0.1`?

**Comment by beubzz** [comment]
Yeah ! perfect, it's working for me now ! thanks a lot !
And i didn't use @asymmetrik/ngx-leaflet@5.0.1 because i'm using Angular 6 and the @asymmetrik/ngx-leaflet@5.0.1 is for Angular 7 right ?
But in all case that's working perflectly righyt now so many thanks for your reactivity ;)

**Comment by reblace** [comment]
Should be fixed now.

**Comment by falco442** [comment]
I'm using the v4.0.0. What am I supposed to do?

**Comment by reblace** [comment]
v4 of ngx-leaflet?

**Comment by edjm1971** [comment]
Sorry if this is not the place to ask, but is there a version that is supported with Angular 6.x.x?
I'm running into brick walls, so if you have any tips I'd appreciate them.
Upgrading to 7.x is not an option at this time.
