### ISSUE TITLE
Namespace leaflet.Draw has no exported member 'Control'

### ISSUE THREAD

**Issue by wmqsoft** [Asymmetrik/ngx-leaflet-draw#71]
<div 
        leaflet 
        leafletDraw
        [leafletOptions]="options" 
        (leafletMapReady)="onMapReady($event)"
        (leafletDrawCreated)="onMapDrawCreated($event)"
        class="map h-100"></div>

    onMapDrawCreated(drawControl: Draw.Control) {
           console.log('add layer');
    }

Here Draw.Control not found

**Comment by benboughton1** [comment]
Or try
```
import {
  ...
  Draw,
  Control,
  DrawEvents
} from 'leaflet';

onMapDrawCreated(drawControl: Control) {
       console.log('add layer');
}
```
