### ISSUE TITLE
How can I add the drawing layer to layerscontrol

### ISSUE THREAD

**Issue by jegjessing** [Asymmetrik/ngx-leaflet-draw#73]
I would like to be able to switch drawings on and off.
Also I would like to have several drawing layers.
I.e. drawingLayer1
drawingLayer2
and be able to turn each layer on and off.

**Comment by jegjessing** [comment]
Sorry! RTFM :-)
edit: {
   featureGroup: <layer>
}

Were to fast. Again - thanks for your great work!

**Comment by reblace** [comment]
Closing since the issue was resolved
