### ISSUE TITLE
Compile time error while migrating angular8 and typescript 3.4

### ISSUE THREAD

**Issue by maheshchari** [Asymmetrik/ngx-leaflet-draw#75]
`ERROR in node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(8,28): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index".Control' has no exported member 'Draw'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(10,28): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index".Control' has no exported member 'DrawConstructorOptions'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(11,39): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index".Control' has no exported member 'Draw'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(12,35): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(13,34): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(14,35): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(15,33): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(16,32): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(17,34): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(18,37): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(19,36): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(20,38): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(21,38): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(22,36): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(23,39): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(24,38): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(25,41): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(26,41): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(27,41): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index"' has no exported member 'DrawEvents'.
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts(34,33): error TS2694: Namespace '"/home/mahesh/ui-framework/node_modules/@types/leaflet/index".Control' has no exported member 'Draw'.
node_modules/@types/esri-leaflet/index.d.ts(9,16): error TS2300: Duplicate identifier '"leaflet"'.
node_modules/@types/esri-leaflet/index.d.ts(259,41): error TS2304: Cannot find name 'Layer'.
node_modules/@types/esri-leaflet/index.d.ts(259,51): error TS2304: Cannot find name 'Content'.
node_modules/@types/esri-leaflet/index.d.ts(259,62): error TS2304: Cannot find name 'Content'.
node_modules/@types/esri-leaflet/index.d.ts(259,72): error TS2304: Cannot find name 'Popup'.
node_modules/@types/esri-leaflet/index.d.ts(259,89): error TS2304: Cannot find name 'PopupOptions'.
node_modules/@types/esri-leaflet/index.d.ts(340,51): error TS2304: Cannot find name 'LatLngExpression'.
node_modules/@types/esri-leaflet/index.d.ts(1110,12): error TS2339: Property 'esri' does not exist on type 'typeof import("/home/mahesh/ui-framework/node_modules/@types/leaflet/index")'.
node_modules/@types/leaflet-draw/index.d.ts(12,16): error TS2300: Duplicate identifier '"leaflet"'.
node_modules/@types/leaflet-draw/index.d.ts(26,12): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet-draw/index.d.ts(50,24): error TS2304: Cannot find name 'Class'.
node_modules/@types/leaflet-draw/index.d.ts(53,19): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(59,24): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(67,24): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(149,18): error TS2304: Cannot find name 'FeatureGroup'.
node_modules/@types/leaflet-draw/index.d.ts(166,26): error TS2709: Cannot use namespace 'Control' as a type.
node_modules/@types/leaflet-draw/index.d.ts(207,11): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(207,18): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(209,16): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(209,23): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(230,19): error TS2304: Cannot find name 'PathOptions'.
node_modules/@types/leaflet-draw/index.d.ts(305,19): error TS2304: Cannot find name 'PathOptions'.
node_modules/@types/leaflet-draw/index.d.ts(321,19): error TS2304: Cannot find name 'PathOptions'.
node_modules/@types/leaflet-draw/index.d.ts(423,11): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(423,18): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(447,26): error TS2304: Cannot find name 'PathOptions'.
node_modules/@types/leaflet-draw/index.d.ts(480,25): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet-draw/index.d.ts(482,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(496,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(503,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(510,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(517,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(523,22): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(530,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(537,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(542,25): error TS2304: Cannot find name 'Class'.
node_modules/@types/leaflet-draw/index.d.ts(543,21): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(549,27): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(562,11): error TS2304: Cannot find name 'Circle'.
node_modules/@types/leaflet-draw/index.d.ts(562,20): error TS2304: Cannot find name 'CircleMarker'.
node_modules/@types/leaflet-draw/index.d.ts(562,35): error TS2304: Cannot find name 'Marker'.
node_modules/@types/leaflet-draw/index.d.ts(562,44): error TS2304: Cannot find name 'Polygon'.
node_modules/@types/leaflet-draw/index.d.ts(562,54): error TS2304: Cannot find name 'Polyline'.
node_modules/@types/leaflet-draw/index.d.ts(562,65): error TS2304: Cannot find name 'Rectangle'.
node_modules/@types/leaflet-draw/index.d.ts(574,12): error TS2304: Cannot find name 'LayerGroup'.
node_modules/@types/leaflet-draw/index.d.ts(584,12): error TS2304: Cannot find name 'LayerGroup'.
node_modules/@types/leaflet-draw/index.d.ts(605,12): error TS2304: Cannot find name 'LayerGroup'.
node_modules/@types/leaflet-draw/index.d.ts(619,11): error TS2304: Cannot find name 'Layer'.
node_modules/@types/leaflet-draw/index.d.ts(626,11): error TS2304: Cannot find name 'Layer'.
node_modules/@types/leaflet-draw/index.d.ts(633,12): error TS2304: Cannot find name 'LayerGroup'.
node_modules/@types/leaflet-draw/index.d.ts(635,10): error TS2304: Cannot find name 'Polyline'.
node_modules/@types/leaflet-draw/index.d.ts(635,21): error TS2304: Cannot find name 'Polygon'.
node_modules/@types/leaflet-draw/index.d.ts(673,38): error TS2304: Cannot find name 'LatLngLiteral'.
node_modules/@types/leaflet-draw/index.d.ts(701,34): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(701,45): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(706,32): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(706,41): error TS2304: Cannot find name 'LatLng'.
node_modules/@types/leaflet-draw/index.d.ts(711,21): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(719,21): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@types/leaflet-draw/index.d.ts(731,11): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(731,18): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(732,16): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(732,23): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(737,15): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(737,22): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(738,17): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(738,24): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(739,20): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(739,27): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(740,22): error TS2304: Cannot find name 'Icon'.
node_modules/@types/leaflet-draw/index.d.ts(740,29): error TS2304: Cannot find name 'DivIcon'.
node_modules/@types/leaflet-draw/index.d.ts(751,24): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet-draw/index.d.ts(755,22): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet-draw/index.d.ts(761,34): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet-draw/index.d.ts(762,37): error TS2304: Cannot find name 'LatLngExpression'.
node_modules/@types/leaflet-draw/index.d.ts(770,29): error TS2304: Cannot find name 'Handler'.
node_modules/@types/leaflet/index.d.ts(11,1): error TS2300: Duplicate identifier '"leaflet"'.
`

Dependence 
    "leaflet": "^1.3.4",
    "leaflet-draw": "^1.0.2",
    "leaflet-heatmap": "^1.0.0",
    "leaflet-polylinedecorator": "^1.6.0",
    "leaflet-textpath": "^1.2.0",
    "leaflet.markercluster": "^1.4.1",
"@asymmetrik/ngx-leaflet": "^5.0.2",
"@asymmetrik/ngx-leaflet-draw": "^4.1.0",
"@types/leaflet": "^1.4.4",
 "@types/leaflet-draw": "^0.4.14",

Node environment 

Node 12.40
Angular 8
typescript 3.40

**Comment by reblace** [comment]
Working on the Angular 8 release now.

**Comment by reblace** [comment]
Angular 8 is out now. Try upgrading and see if you still have the issue.
