### ISSUE TITLE
handleEvent' does not exist on type 'typeof LeafletUtil

### ISSUE THREAD

**Issue by austin92jus** [Asymmetrik/ngx-leaflet-draw#84]
while import leaflet drw modules its shows handleEvent' does not exist on type 'typeof LeafletUtil

**Comment by reblace** [comment]
The latest versions of ngx-leaflet and ngx-leaflet-draw fix this issue. You might be mismatching versions if you're still getting this error. Try upgrading to the latest matched versions.
